callstack/react-native-pager-view

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java
Imported from https://github.com/facebook/react-native/pull/18609
---
Currently, when adding views to ViewPagerAndroid after it was attached, those views would not show up as they had a size of 0. This fixes that by measuring and layouting after adding a view to the container.
Fixes https://github.com/facebook/react-native/issues/14296
See https://github.com/danilobuerger/react-native-viewpagerandroid-dynamic
1. yarn install
2. yarn run android
3. You will see two pages
4. Press "ADDPAGE"
5. Scroll to the third page, it will be empty
6. Use react-native master with this patch
7. yarn run android
8. You will see two pages
9. Press "ADDPAGE"
10. Scroll to the third page, it will show "3 page (Scroll Me)"
=> measure and layout after adding a view to the container

js/ViewPagerAndroid.android.js
`UIManager.getViewManagerConfig` does not exist on RN <= 0.57. Added fallback for that case.
=> compat with <= rn57

ios/ReactNativePageView.m
Close https://github.com/react-native-community/react-native-viewpager/issues/99
Close https://github.com/react-native-community/react-native-viewpager/issues/96
=> fix: scrollEnabled prop, when comp is loaded dynamically

README.md, example/ViewPagerExample.js, example/ios/Podfile.lock, ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m, js/types.js, typings/index.d.ts
Closes #63
It's a missing feature compared to the ScrollView and it's quite easy to implement this
https://stackoverflow.com/questions/21798218/disable-uipageviewcontroller-bounce
https://streamable.com/6kwf6
Running the example app on iOS should be ehough
Run example (added buttons)
=> Add overdrag property on iOS

ios/ReactNativePageView.m
In ViewPager previously touches in UIControl (Button from RNGH) were a bit delayed which is expected from one side (because gestures can negotiate better), but it's not used in React Native (in normal ScrollView) and leads to bad UX. 
Example: 
before:
https://streamable.com/f8doo
after:
https://streamable.com/457s3
Install RNGH and add some button 
Install RNGH and add some button 
| Android |     ¯\_(ツ)_/¯      |
=> Remove delaying touches in ScrollView

README.md, example/ViewPagerExample.js, example/ios/Podfile.lock, ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m, js/types.js, typings/index.d.ts
Reverts react-native-community/react-native-viewpager#107
It sometimes breaks on iOS. Pager stucks in the middle of the animation. Until I figure out what's wrong, I need to revert this
=> Revert "Add overdrag property on iOS"

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, example/ios/Podfile.lock, ios/ReactViewPagerManager.m, js/ViewPager.js
Fixes #112.
Summary is in #112.
Can be tried using `this.viewPager.current.setScrollEnabled(false)` (or `true`) anywhere in our example. I am not adding this in the `README` as is kind advanced / not recommended.
=> feat: add imperative setScrollEnabled method

example/ios/Podfile, example/ios/Podfile.lock, example/ios/postinstall.sh
Cocoa pods does not support local dep, so I decided to copy local files inside `Pod` dir. 
Cocoapods will automatically link lib and postinstall script will copy files from `ios` to Pod dir.  
* Make some changes inside `ios` file
* Check, if those changes are inside Pod file
=> feat: add postinstall script.

js/ViewPager.js, js/types.js, typings/index.d.ts
On Android when ViewPager is scrolling with swipe gesture all content(including all Touchables) are disabled. On iOS it's not - all touchables are interactable while swiping so when viewpager content has button or other clickable components they are clicked.
Close #73 
Click on button, while scrolling. Check if no of likes increased. 
| iOS     |    ✅  |
=> [iOS] Disable content touches when ViewPager is scrolling

example/ios/Podfile, example/ios/Podfile.lock
This small change makes developing for iOS a bit better. It uses development pods, which makes any change in Pods to be local.
1. Open Example app (through Xcode)
2. Run project (remember to run packager)
3. In `Pods` project, find `Pods -> Development Pods -> react-native-viewpager`
4. Those files are now local
=> Enhance developer experience for iOS

typings/index.d.ts
fixes `index.d.ts` and removes `any` from the type.
The original `index.d.ts` had `ViewPager` extend `ViewProps`, but in the flow type, defined in https://github.com/react-native-community/react-native-viewpager/blob/master/js/types.js, it does not actually extend `ViewProps`, it only uses `ViewProps` to get the required type for `onMoveShouldSetResponderCapture`
=> update index.d.ts to match flowtype

ios/ReactNativePageView.m
That PR fixes issue that can appear when you  delete multiple views inside viewpager on iOS.
| Android |    N/A     |
=> Fix for deleting multiple views on iOS

ios/ReactNativePageView.m
Progress view display wrong value once user is scrolling vertically
Close https://github.com/react-native-community/react-native-viewpager/issues/127
* Set orientation to vertical 
* Check, if progress bar displays correct value
=> [iOS] fix: vertical scroll progress

example/ViewPagerExample.js, example/src/component/ProgressBar.js, ios/ReactNativePageView.m
When VP has no children, app crashed 
Close https://github.com/react-native-community/react-native-viewpager/issues/145
Set initial page value to empty array like below: 
```
this.state = {
page: 0,
pages: [],
};
```
And app will crash 
| iOS     |    ✅ |
=> [iOS] fix: crash on empty array

typings/index.d.ts
With the latest changes in typings (e12c183636f3b69c8e2408ccf82318b133034e74) as an attempt to match Flow and TypeScript, `ReactChildren` was used as children type. This is not the correct one, AFAIK. The typical children type is `ReactNode` which is defined as:
```ts
type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```
This is a change in the typings and there are no proper test cases for this in the repo, but this has been tested in an actual project where the issue with mistypes occurred.
---
This PR Fixes #165
=> fix: Set type on children as ReactNode in typings

ios/ReactNativePageView.m
Hi,
I realized on iOS `onPageSelected` can fire even when the transition is not completed.
Checking out [Apple documentation](https://developer.apple.com/documentation/uikit/uipageviewcontrollerdelegate/1614090-pageviewcontroller?language=objc), we should use the `completed` boolean to make sure the event fires only when transition is completed.
The code below is enough to reproduce:
```js
const App = () => {
return (
<ViewPager
style={styles.viewPager}
initialPage={0}
onPageSelected={({ nativeEvent: { position } }) => {
alert(position);
}}
>
<View key="1" style={{ backgroundColor: "yellow" }}>
<Text style={{ fontSize: 30 }}>First page</Text>
</View>
<View key="2" style={{ backgroundColor: "blue" }}>
<Text style={{ fontSize: 30 }}>Second page</Text>
</View>
</ViewPager>
);
};
```
Using …
=> fix: prevent onPageSelected from firing too often on iOS

ios/ReactNativePageView.m
Found inspiration in https://github.com/software-mansion/react-native-gesture-handler/pull/997:
This pull request implements event coalescing on `onPageScroll` event on iOS. 
Event coalescing is a built-in mechanism from React Native's event-emitter that merges several events together when events are generated faster on the native thread than they can be handled on the Javascript thread. This prevents accumulating lag when JS thread is under heavy load (or on low-end devices).
NB: coalescing is [the default on Android](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java#L56) so no changes on Android were required
This PR basically implements the same behavior on iOS.
The code below uses the fibonacci function to …
=> perf: implement coalescing for onPageScroll on iOS

ios/ReactNativePageView.m
Fixes app crash because of UIViewControllerHierarchyInconsistency
[issue](https://github.com/react-native-community/react-native-viewpager/issues/167)
Tested on simulator and real device
=> Fix UIViewControllerHierarchyInconsistency

README.md, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, js/types.js, typings/index.d.ts
I think it's useful to expose this property. I find it important in my app where I don't want to have the overscoll shade visible. 
https://streamable.com/ohupov
after setting `overScrollMode="never"`
try to scroll over the bounces. 
=> Add support for overScrollMode on Android

android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, android/src/main/java/com/reactnativecommunity/viewpager/ViewPagerFragment.java
Sometimes when navigating through an app and then returning to previous screens, the Viewpager can show blank pages. After bit of debugging on Java side, I noticed a bug that causes ReactViewpagerManager to discard wrong Views on calls to `removeView(Viewpager2, int)`. It uses the int as an index on the `reactChildrenViews` SparseArray it has directly, even though it should use it to find the correct child inside of that Viewpager2 parent parameter. So I changed it to properly do that child View lookup and then use the `removeView(Viewpager2, View)` method to do the actual View removal.
While fixing ReactViewpagerManager I also changed the `FragmentAdapter#getChildAt(int)` to also work on Fragments that haven't retrieved their View from ReactViewpagerManager yet, as otherwise my changes …
=> fix: Android ReactViewpagerManager destroys wrong Views

android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java
In Android, when component collection sent to the ViewPager mutates for some reason (eg. a list of questions in which the next question depends on the previous answer, see example below), the `ViewPagerFragment` will return an empty view.
After a little debugging, I realized the observers weren't being notified of the change through `notifyDataSetChanged()`. As stated in [Android's documentation](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/RecyclerView.Adapter#notifydatasetchanged), it is more efficient to specify the event change.
> If you are writing an adapter it will always be more efficient to use the more specific change events if you can. Rely on notifyDataSetChanged() as a last resort.
Impacts on Android only.
=> fix: Android returning blank view when collection mutates

react-native-viewpager.podspec
https://github.com/react-native-community/react-native-webview/pull/1643
=> fix(ios): autolinking when using Xcode 12

ios/ReactNativePageView.h
Add the import for RCTEventDispatcher, it seems like it is no longer transitively imported from RCTViewManager. It is better to explicitly import it anyway.
Tested that adding this import fixes my app build that is based on RN master.
N/A
N/A
=> Add missing RCTEventDispatcher import

android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java
When there are multiple pagers, especially if some are dynamically created/removed, pages can disappear.  This only occurs on Android due to clearing the entire static array.
| iOS     |    ✅ (already works)     |
=> Fix Android multiple pager instances

react-native-viewpager.podspec
When running a build on the command line, I get the following warning:
```
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.7.99. (in target 'react-native-viewpager' from project 'Pods')
```
Since the recent iOS minimum for React Native is 9.0, I updated the .podspec to match it.
1. Updated the podspec in my application's `node_modules` folder.
2. Ran an Xcode build.
3. Verified no warnings about `IPHONEOS_DEPLOYMENT_TARGET`
N/A
N/A
| Android |    N/A     |
=> Fix Xcode build warning about IPHONEOS_DEPLOYMENT_TARGET

android/build.gradle, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, example/ios/Podfile.lock
Fix for issue https://github.com/callstack/react-native-viewpager/issues/231
Prepare testing component with this body:
```jsx
<SafeAreaView style={{flex: 1, backgroundColor: 'white'}}>
<ViewPager pageMargin={24} style={{flex: 1}}>
<View style={{flex: 1, backgroundColor: 'red'}} />
<View style={{flex: 1, backgroundColor: 'blue'}} />
</ViewPager>
<View style={{flex: 1, backgroundColor: 'yellow'}} />
<ViewPager pageMargin={24} style={{flex: 1}} orientation="vertical">
<View style={{flex: 1, backgroundColor: 'green'}} />
<View style={{flex: 1, backgroundColor: 'tomato'}} />
</ViewPager>
</SafeAreaView>
```
=> fix: add android pageMargin

android/build.gradle, android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, android/src/main/java/com/reactnativecommunity/viewpager/ViewPagerFragment.java, src/ViewPager.tsx
Fix for issue https://github.com/callstack/react-native-viewpager/issues/164
There are multiple solutions in issue i've tested this one and it works.
It contains also a few improvements like:
- remove unnecessary fork of ViewPager2
- change storing views approach on android
=> fix: prevent touch events to be executed during swipe

README.md, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, lib/typescript/src/types.d.ts, src/types.ts
I need this so deeply https://developer.android.com/reference/androidx/viewpager2/widget/ViewPager2#setOffscreenPageLimit(int)
Basically, I have a ton of things rendered on pages and do not want to optimize it, because it leads to some minor glitches 
Before: 
https://streamable.com/psex6e
After:
https://streamable.com/nq5yvb
Doesn't have too much impact unless the app is really packed with components. 
=> Add offscreen page limit

example/ios/ViewpagerExample.xcodeproj/project.pbxproj, ios/ReactNativePageView.m
Partially fix problem from this issue https://github.com/callstack/react-native-viewpager/issues/167
Problem exists only when value of `initialPage` is same as `setPage` executed from `componentDidMount`
<details>
<summary>Code which caused crash before</summary>
```ts
import React, {useRef, useState, useEffect} from 'react';
import {Image, StyleSheet, Text, View, SafeAreaView} from 'react-native';
import ViewPager from '@react-native-community/viewpager';
export default () => {
const viewpagerRef = useRef(null);
const [pages, setPages] = useState([
<Image
source={{uri: 'https://lorempixel.com/1080/1920/sports/2/'}}
style={styles.image}
key={1}
/>,
<Image
source={{uri: 'https://lorempixel.com/1080/1920/sports/4/'}}
style={styles.image}
key={2}
/>,
<Image
source={{uri: …
```
=> fix: app crashing while setPage in componentDidMount on IOS

README.md, example/src/BasicViewPagerExample.tsx, example/src/component/NavigationPanel/ControlPanel.tsx, example/src/hook/useNavigationPanel.ts, ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m, lib/typescript/example/src/component/NavigationPanel/ControlPanel.d.ts, lib/typescript/example/src/hook/useNavigationPanel.d.ts, lib/typescript/src/types.d.ts, src/types.ts
Closes #120  
It's a missing feature which was reverted in certain version which allows to disable/enable bounce effect while scrolling on iOS.
https://stackoverflow.com/questions/21798218/disable-uipageviewcontroller-bounce
=> chore: add prop to disable/enable scroll bounces

src/utils.tsx
Due to creating new children of ViewPager instance rather than cloning them we were losing properties like `ref`.
This issue is better described in #224.
=> fix: clone children's instead of creating new ones

android/src/main/java/com/reactnativecommunity/viewpager/ViewPagerFragment.java
Basically it's an attempt to fix an issue reported in #283 and #282 which are seems to be related with restoring fragments state and creating ViewPagerFragment class without arguments.
Unfortunately, because this error not occurs on local environment, before we'll try to find some better solution we want to make sure that our guess is proper by implementing constructor without any arguments and check if it's helped.
=> chore: add empty constructor

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java
v5 regression
1. use setPageWithoutAnimation on Android
2. animation occurs
| iOS     |    ✅   |
=> fix v5 regression: broken setPageWithoutAnimation

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java
Similar bug to this: https://github.com/callstack/react-native-viewpager/pull/271
Longcat: `Scrapped or attached views may not be recycled`
Fix just removes touch event execution when component is unmounting. Maybe there is some nicer way to fix this error, but I haven't found it...
Render the instance of ViewPager inside of createNativeStackNavigator screen.
Enter to the screen and try to leave it by clicking back and then (very fast) try to swipe (during the screen removal animation).
It's hard to reproduce this bug in simulator. The easiest way is to just add timeout to the screen with `goBack()` running after a few seconds.
=> fix (android): crash when scroll during unmount

ios/ReactNativePageView.m
onPageScroll event offset value was not unified for android and iOS. Previously value could be negative, whereas on Android all values are positives.  
=> fix(ios): onPageScroll event offset value

ios/ReactNativePageView.h, ios/ReactNativePageView.m
fix onPageSelected event
Closes #297 
=> fix(ios): onPageSelected event

src/PagerView.tsx
fix #312 with workaround solution from @KusStar (see https://github.com/callstack/react-native-pager-view/issues/312#issuecomment-807846238)
=> fix #312 - no initial page load on Android

ios/ReactNativePageView.h, ios/ReactNativePageView.m
this fixes an issue where `onPageSelected` callback is not fired on ios when it should
how to reproduce the bug:
- render pager with 2 pages
- swipe from page index 0 to 1
- after running `self.previousIndex = currentIndex - 1;`, `self.previousIndex` will contain `0`
- now call `ref.current?.setPage(0)`. That triggers  the native listener and `if(_previousIndex != _currentIndex)` from line 177 will be `false` and so `[weakSelf.eventDispatcher sendEvent...` is not called and so `onPageSelected` callback is not fired in JS
the test plan followed the steps and the bug can no longer be reproduced
- ios simulator
=> fix: onPageSelected not called on ios

README.md, android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, ios/ReactNativePageView.m
the motivation is to unify cross-platform behavior around `setPage` edge cases. Consider pager with 3 pages, and you're currently on the middle page (index==1)
if we call  `setPage(-1)`
- iOS: nothing happens
- android jumps to index 0 but `onPageSelected` reports index equal to -1
if we call  `setPage(10)`
- iOS: scrolls to last page, `onPageSelected` reports correct index (2)
- android jumps to last page but `onPageSelected` reports index equal to 10
this PR unifies the behavior so that when the index passed to `setPage` is invalid, nothing happens. I can change this if desired (eg. out of bounds indices would jump to index 0 or to the end), but the idea is that both platforms behave the same.
I also documented the methods in the readme, and my vscode extension prettified it so there …
=> fix: unify setPage behavior across platforms

src/PagerView.tsx
Fixes #339: If the component unmounts immediately after mounting, then the call to requestAnimationFrame will attempt to operate on the unmounted component. We can prevent this by ensuring we cleanup the callback on unmounting.
Manually tested using reproduction steps of bug. A before and after gif is included below. The examples below test this change in a fairly tight loop, hence the error appearing multiple times in the console output. There's also some diagnostic logging that doesn't feature in this PR:
- NodeJS
- Android Emulator
```
npx create-react-native-app foobar (accept default)
npm install react-native-pager-view
```
Modify `App.js` to contain the following, which is a slight modification from the bug reproduction steps:
```
import { StatusBar } from 'expo-status-bar';
import …
```
=> Fixes #339 - Handle the component unmounting

example/src/App.tsx, example/src/BasicPagerViewExample.tsx, example/src/HeadphonesCarouselExample.tsx, example/src/KeyboardExample.tsx, example/src/LazyPagerViewExample.tsx, example/src/OnPageScrollExample.tsx, example/src/OnPageSelectedExample.tsx, example/src/PaginationDotsExample.tsx, example/src/ScrollViewInsideExample.tsx, example/src/ScrollablePagerViewExample.tsx, example/src/hook/useNavigationPanel.ts, example/src/utils.ts, package.json, src/LazyPagerView.tsx, src/PagerView.tsx, src/PagerViewNative.tsx, src/index.tsx, src/types.ts, yarn.lock
Enables pages to be rendered on demand, instead of all at once.  This is the JS specific changes.  Several parts are commented out, awaiting the associated native changes.
Split from #279.  Note that due to lack of native support (will be done in another pr), all pages prior to the current page will always be rendered.  So starting in the middle/end of a large number of pages is not very efficient.  Also, pager will not navigate to a page until the page is rendered (requires native support).  This can lead to feeling stuck if swiping quickly through heavy pages.
- Checkout of this branch (unmodified).
- Checkout of this branch, patched to show renders.
<details>
<summary><tt>track-page-renders.patch</tt></summary>
```diff
diff --git a/example/src/BasicPagerViewExample.tsx …
```
=> Lazy pager (js side)

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
Fixes https://github.com/callstack/react-native-pager-view/issues/349
Removing a page on Android was resulting in a white screen until you interacted with the ViewPager. The issue appears to be related to this historical React Native issue https://github.com/facebook/react-native/issues/17968 where by custom Android native UI modules don't re-layout correctly on certain occasions. I introduced the workaround as outlined here https://github.com/facebook/react-native/issues/17968#issuecomment-697136929 to refresh the pager when a page is removed.
**Before**
**After**
Create a pager with 3 pages and run on an Android device. 
Delete the 2nd page.
See https://github.com/callstack/react-native-pager-view/issues/349 for steps to reproduce original issue.
| ------- | …
=> fix(android): Allow pages to be removed

android/src/main/java/com/reactnativepagerview/FragmentAdapter.kt, android/src/main/java/com/reactnativepagerview/PagerDiffCallback.kt, android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, src/LazyPagerView.tsx, src/PagerView.tsx, src/PagerViewNative.tsx, src/types.ts
Enables pages to be rendered on demand, instead of all at once. This is the Android native code changes.
Split from #279. Note that this builds on top of #326, so when reviewing code, may be easier to check the specific commits that are not in #326.
- Checkout of this branch (unmodified).
- Checkout of this branch, patched to show renders.
<details>
<summary><tt>track-page-renders.patch</tt></summary>
```diff
diff --git a/example/src/BasicPagerViewExample.tsx b/example/src/BasicPagerViewExample.tsx
index 48ad5a4..69df7a3 100644
--- a/example/src/BasicPagerViewExample.tsx
+++ b/example/src/BasicPagerViewExample.tsx
@@ -15,6 +15,17 @@ function keyExtractor(page: CreatePage) {
}
function renderItem({ item }: { item: CreatePage }) {
+  return <TrackingRender item={item} />;
+}
+
+function …
```
=> Lazy pager (Android native side)

ios/ReactNativePageView.m
When disabling overDrag on iOs and swiping right on the first page to trigger it the `offset` would change between `0` and `0.05...`. This can be seen on the Headphone example. ( need to add `overDrag={false}` prop to the pager component ) 
I fixed it by setting the `offset` to `0` when it goes into the `!_overDrag` logic.
Before:
https://user-images.githubusercontent.com/50402950/119804695-e17dc580-bee0-11eb-9946-d080ba9c945e.mp4
After:
https://user-images.githubusercontent.com/50402950/119805009-299ce800-bee1-11eb-968e-1cecf723b710.mp4
=> fix(ios): offset is changing  while overDrag is disabled

ios/ReactNativePageView.m
Solves #388.
Adds support for disabling overdrag in vertical mode.
Run `Basic Example` with `orientation="vertical"` option.
When first slide is active, try to scroll up - it animates bounce effect even when `overdrag` option is set to `false`
=> fix(ios): Allow disabling overdrag in vertical orientation

ios/ReactNativePageView.m
Closes #109
On iOS removing last page while it is displayed resulted in blank screen rendered.
This change adjust the behavior to display closest remaining page instead.
Before changes:
https://user-images.githubusercontent.com/746000/126478510-a2e42970-6b2a-4e59-bfb1-4dcbc33f98e9.mov
After changes:
https://user-images.githubusercontent.com/746000/126478533-42ddd4b0-7291-447d-b63e-532f1d092c2b.mov
Open `Basic example`
Navigate to the last page and click `remove last page`
=> fix(ios): removing last page

example/src/component/ProgressBar.tsx, ios/ReactNativePageView.m
Closes #330
On iOS there was an issue with progress values emitted during overdrag gesture.
During overdragging to the left, progress was positive, instead of negative.
As discussed in #330 - applied solution is to return `position: -1` during left overdrag which indicates the active page is negative. This way if neccessary user can consume negative offset, or simply clamp it within `<0, 1>` if negative values are not expected (i.e. `0-100%` progress bar in the examples control panel)
Before changes:
https://user-images.githubusercontent.com/746000/126484187-027ee2bd-f06d-4e03-b198-69b9cc011896.mov
After changes:
https://user-images.githubusercontent.com/746000/126484196-0c82c509-fdbd-4dc6-9024-abdb950e79b4.mov
Open `Headhpones Example` with `overdrag={true}`.
Swipe left to see overdrag …
=> fix(ios): emit correct progress values for overdrag

android/src/main/java/com/reactnativepagerview/Helper.kt, android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
Closes #394 
`getReactContext` method is missing in the older versions of react native. Moved this [method](https://github.com/facebook/react-native/blob/v0.64.2/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerHelper.java#L138) to the codebase. 
=> fix(android): implement getContext for the older versions of react native

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, ios/ReactNativePageView.m, src/PagerView.tsx
Closes #367
When `layoutDirection` was `locale` or `undefined`, device RTL was incorrectly deduced.
Solution was to move the detection from native part to the `react-native` part, using `I18Manager.isRTL` property. Now it should better and more consistently recognise device RTL setup.
Open PagerView with `layoutDirection="locale"` or with `layoutDirection` undefined.
Set `I18nManager.forceRTL(true)` to use RTL layout for the app.
Open the pager and see layout is deduced from the app setup and the pager uses `RTL` layout by default.
=> fix: deducing rtl device setup

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, src/PagerView.tsx
Closes #400
On Android, setting initial page was implemented asynchronously on React side and native `onPageSelected` was fired twice (with default value and then with proper one).
This PR moves the implementation directly to `ViewPager2` API.
Setup `Basic Example` with `initialPage={1}` and with `onPageSelected={(e: any) => console.log(e.nativeEvent.position)}`
Open the Example and see what pages are reported in `onPageSelected` callback
=> fix(android): set initial page natively

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, ios/ReactNativePageView.m
Closes #219
Both iOS and Android implementations had issues when the `PagerView` was initially rendered with empty pages set.
Android: blank page was rendered, proper page appeared after user's first interaction
iOS: blank page was rendered, it didnt appear even after first interaction
This PR fixes handling initially empty sets on both platforms.
Render pager with empty pages initially set and add more pages on the fly.
See pages are now rendered correctly.
=> fix: initially empty views

src/LazyPagerView.tsx
It's too long when call `setPage` method if is running other animation. I thought its waiting for other animation frame. So, I tried change`requestAnimationFrame` to `setTimeout`.
It looks smoother.
| Android |    ✅   |
=> fix setPage call to long

ios/ReactNativePageView.m
`addSubview` method removes the previous parent, hence this error should not occur. 
Close https://github.com/callstack/react-native-pager-view/issues/167
| iOS     |    ✅  |
=> fix(ios): UIViewControllerHierarchyInconsistency error

README.md
The NPM badge was still poiting to the old package name. Just updating the readme so the correct version is shown.
N/A
=> Update NPM badge in readme to target `react-native-pager-view`

example/ios/Podfile.lock, example/src/App.tsx, ios/ReactNativePageView.m
Closes #454 
`onPageSelected` fires for every page in between the range.
https://user-images.githubusercontent.com/12766071/135571785-ab307ee7-18a3-4eda-8d53-9be45c64ffe1.mov
=> fix(ios): multiple onPageSelected calling

README.md
In the docs, the link after the "Usage" code snippet talks about setting collapsable to false and the link to the documentation on collapsable is broken. I've updated it to point to the proper resource.
Click the link.
=> docs: update link to react native's view's collapsable docs

README.md, example/android/app/build.gradle, example/android/app/src/main/java/com/example/reactnativepagerview/MainApplication.java, example/babel.config.js, example/ios/Podfile.lock, example/package.json, example/src/App.tsx, example/src/ReanimatedOnPageScrollExample.tsx, example/yarn.lock
This PR adds a document section to integrate reanimated event handler with onPageScroll. Ideally it would be more convenient to export a hook `useAnimatedPageScrollHandler` but it'll add dependency on reanimated. I think creating a separate package for this hook can also be convenient!
- I have [created a gist](https://gist.github.com/intergalacticspacehighway/52252474872c9e2246e398179920ccf2) which can be tested in RN example app which has reanimated installed and configured. The callback receives offset and position events. 
- Also this [repo](https://github.com/intergalacticspacehighway/pager-view-reanimated-repro) (App.js) includes the working example which can be referred.
- I am not really sure if there are any more cases.
- react-native-pager-view and react-native-reanimated
- Run …
=> add docs for attaching onPageScroll handler with reanimated

ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m
This PR resolves issue: https://github.com/callstack/react-native-pager-view/issues/458
Working demo of no crash when tab switching quickly:
https://user-images.githubusercontent.com/85892917/152933713-fc860143-46b6-4b91-9600-4441fc3171bf.mp4
Use the example app.
Switch back and forth between tabs super quickly and observe a crash.
- [✅] I have tested this on a device and a simulator
=> fix(ios): Crash when rapidly switching pages

ios/ReactNativePageView.m
Introduced in #455 this should have been `i` instead of `index` all along.
Rapidly go backwards as described in #458 .
=> Fix wrong variable usage that causes crash related to #458

ios/ReactNativePageView.m
This PR is a better fix for the following problem. https://github.com/callstack/react-native-pager-view/issues/515. 
The rapid tap causes the setViewControllers function in UIPageViewController to not execute the completion block. When the completion block is not executed, the pager view gets in an invalid state and blocks any attempts to set a different page.
In this fix there is an extra check wether the controller that is set, is the same that is already in the UIPageViewController. If so, no animation is done and the completion block is executed. This makes sure that the completion block is always executed.
- [X ] I have tested this on a device and a simulator
=> Fixed potential blocking of the navigation

android/src/main/java/com/reactnativepagerview/NestedScrollableHost.kt, android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
Whenever using initialPage != 0 on Android there is a 1 frame flicker where you can see the page at index 0 displayed before the right page at initialPage is displayed. This happens because the setting of the initial page is delayed in https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L151
To compensate for not knowing (due to a limitation in rn) how many children are initially added, this also tracks that initial page is only set in the initial render.
Use a PagerView with initialPage != 0 and record the render. Step through the video frame by frame, you will see it jumping on first render.
=> Prevent 1 frame flicker on android if initialPage != 0

ios/ReactNativePageView.m
In case of setting UIPageViewController.viewControllers to exactly the same controllers, the completion block is not called.
With the introduction of animating in #510, animating will then not be set to NO anymore. 
This will lead to being unable to switch the pages.
Fixes a regression in #510 
cc @doug-lessen
Goto the same page without changing the view, after that switching the page is no longer possible.
=> Return early when new view controller is the same as the old one

src/LazyPagerView.tsx
Animated programmatic page changes when the viewer has a small `maxRenderWindow` may fail to change pages (observed most on iOS), or scroll past then back (observed most on Android).
Fixes #537
In the example project `LazyPagerViewExample.tsx`, reduce `maxRenderWindow` to 5.  With animations enabled, use the next button.
=> fix: animated set page may stick or overshoot

ios/ReactNativePageView.m
Set delaysContentTouches to YES (iOS Default)
If the value of this property is true, the scroll view delays handling the touch-down gesture until it can determine if scrolling is the intent. If the value is false , the scroll view immediately calls [touchesShouldBegin(_:with:in:)](https://developer.apple.com/documentation/uikit/uiscrollview/1619418-touchesshouldbegin). The default value is true.
Not sure why this was set to NO in first place, most likely to be able to determine the users touch intent faster, but it breaks native touchables, like those from react-native-gesture-handler.
Fixes #554
=> fix: set delaysContentTouches to YES (fixes iOS touchable issues)

ios/ReactNativePageView.m
Added additional checks to scroll without animation if already an animation is in progress to fix `NSInternalInconsistencyException` crash in iOS
=> added extra check for `NSInternalInconsistencyException` crash in iOS

ios/ReactNativePageView.m
Fix for #568 
Before fix calling setPageWithoutAnimation starts transition to new page with animation (incorrect).
After fix there is no animation (correct).
- [ x] I have tested this on a device and a simulator
=> fix(ios): restore animated param check

example/ios/Podfile.lock, example/src/KeyboardExample.tsx, ios/ReactNativePageView.h, ios/ReactNativePageView.m, src/utils.tsx
#565 originally fixed this but #567 regressed it.
This should fix it again, more properly this time.
- Open the "ScrollView inside PagerView Example" in an iOS simulator and rotate to landscape.
- Open the Keyboard Example and focus the text input, ensure the keyboard doesn't dismiss
=> fix(ios): incorrect pager height

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
Associate a non-taken Android ID to the `NestedScrollableHost`
`NestedScrollableHost` is created as a new class but never associated an ID. In one of our screen was creating a crash because the default id was already used. 
This was happening when re-recreating the view.
The changes just add a random Android ID not taken already. The test done has been:
Load screens with the page view.
Background and Foreground the app.
Enable Do not Keep Activities settings and do the previous steps.
After the fix should not crash.
This crash was only reproducible on Android
=> fix(android): assign an id to  on Android (#585)

android/src/turbo/PagerViewViewManager.kt
This PR fixes building issue on **Android** which appeared after merging branch implementing Fabric on **Android** into Fabric migration branch.
When working on Fabric for **iOS**, two properties: _overdrag_ and _keyboardDismissMode_ (which are iOS only) were missing in spec file and were added into it, which caused build error on Android to appear.
1. run ``yarn bootstrap-fabric``
2. inside ``fabricexample`` folder run ``yarn android``
=> fix(android): fix fabric build issue

ios/ReactNativePageView.m
When RTL was enabled the forward direction is the other way around. This is why when isForward was true the for loop in line 264 (of updated code) was not running as when forward was true `_currentIndex` is greater than `index` preventing the for loop to happen. This is why when RTL is enabled I make a new variable to check whether it's enabled or not and if it is the isForward should be the opposite as when LTR is enabled.
the issues this pr close are : 
https://github.com/callstack/react-native-pager-view/issues/420
https://user-images.githubusercontent.com/83782787/193692343-dd503612-305b-4bd9-914b-138a25464335.mov
https://user-images.githubusercontent.com/83782787/193692558-cfcd8f7f-c8c1-4e67-a69b-9bec33ce687d.mov
Run example project and test changes out
Go to any pagerview example …
=> fix: on tab selection scroll when rtl enabled

fabricexample/src/App.tsx
Small PR adding missing SafeAreaView to **Fabric** example, which was causing incorrect displaying on devices with notch/dynamic island. Now both examples (Paper and Fabric) have same behavior.
1. run fabric example
=> fix: add missing SafeAreaView to fabric example

ios/Fabric/RNCPagerViewComponentView.mm
This PR fixes issue causing animations not to work on `onPageScroll` event on **Fabric** architecture on **iOS**.
This issue was reported in #618 
1. open **Fabric** example app
2. select example with indicator e.g. _Headphones Carousel Example_
3. scroll to next page - animations should work as expected
=> fix(iOS): fix animation on onPageScroll event on Fabric

ios/Fabric/RNCPagerViewComponentView.mm
This PR fixes issue with incorrect _Pager View_ height causing blank space to appear.
This issue appeared only on **iOS** on **Fabric** architecture.
It was reported in #618 
_Pager View_ should display correctly without blank space in every example on **Fabric**.
=> fix(iOS): fix pager view height issue on Fabric

android/build.gradle
This pull request updates **Pager View** to use `mavenCentral` instead of `jcenter`.
Fixes #501 and #541  
Package should build correctly 
=> fix(android): replace jcenter with mavenCentral

ios/Fabric/RNCPagerViewComponentView.mm
This pull request fixes issue causing keyboard not to appear when focusing text input inside **Pager View** (Fabric only)
1. run `fabricexample`
2. open _Keyboard Example_ 
3. focus input - keyboard should display correctly
=> fix(ios): fix keyboard behavior on fabric

example/ios/Podfile.lock, fabricexample/ios/Podfile.lock, ios/Fabric/RNCPagerViewComponentView.mm, ios/ReactNativePageView.m
This pull request fixes issue causing **Pager View** to freeze after calling _setPage_ method.
It was caused by not re-enabling user interactions in certain situations. 
User interactions are being disabled after calling the _setPage_ method until the transition to the next page is complete, as it caused unexpected **Pager View** behavior.
Also small refactor has been introduced to improve code readability.
**Pager View** should be interactive after calling _setPage_ method (on both **Fabric** and **Paper** architectures)
=> fix(ios): fix freeze after calling setpage

.github/workflows/ios.yml
This PR removes redundant step of installing Pods on CI.
Successful CI build
=> chore: remove CI redundant step

common/cpp/react/renderer/components/RNCViewPager/RNCViewPagerComponentDescriptor.h, common/cpp/react/renderer/components/RNCViewPager/RNCViewPagerShadowNode.cpp, common/cpp/react/renderer/components/RNCViewPager/RNCViewPagerShadowNode.h, common/cpp/react/renderer/components/RNCViewPager/RNCViewPagerState.cpp, common/cpp/react/renderer/components/RNCViewPager/RNCViewPagerState.h, example/src/NestPagerView.tsx, example/src/PaginationDotsExample.tsx, example/src/utils.ts, fabricexample/ios/Podfile.lock, fabricexample/src/NestPagerView.tsx, fabricexample/src/PaginationDotsExample.tsx, fabricexample/src/utils.ts, ios/Fabric/RNCPagerViewComponentView.h, ios/Fabric/RNCPagerViewComponentView.mm, react-native-pager-view.podspec, src/PagerView.tsx, src/utils.tsx
This PR introduces _PagerView_ **Fabric** implementation rewrite from **UIPageView** to **UIScrollView**.
It is based on React Native's **UIScrollView** implementation for  **Fabric**.
As described in #673, we wanted to have more control over native side of _PagerView_ which could be achieved by switching from using **UIPageViewController** to **UIScrollView**. 
This change makes _PagerView_ easier to maintain, because some solutions and workarounds used in previous implementation were adding more complexity and were causing some additional bugs. 
Switching to **UIScrollView** allowed to reduce amount of code and complexity, while maintaining same functionality.
In future it will also be easier to add new features or e.g. custom animations to _PagerView_.
Every example should work as …
=> feat(iOS): change Fabric implementation to UIScrollView

ios/Fabric/RNCPagerViewComponentView.mm, ios/ReactNativePageView.m
This PR fixes last / first page not being set back to idle when bounces are off. 
https://user-images.githubusercontent.com/52801365/213752478-3b52287c-877e-4fdf-907a-644bafaa6a12.mp4
https://user-images.githubusercontent.com/52801365/213752826-6a7c07cc-1ccc-444f-a4af-e1448d133e97.mp4
1. Launch the Pager app
2. Once the PagerView Example page is visible tap the Keyboard Example or the Basic Example tab
3. Then tap the [Next]/ [Prev]/ [Last]/ [Start] button
4. While mentioned above buttons are taped observe the ScrollState [idle] button and check if its state is changing
=> fix: set last/first page as idling when dragging

example/ios/Podfile.lock, example/package.json, example/src/App.tsx, example/src/ScrollablePagerViewExample.tsx, example/src/tabView/CustomIndicatorExample.tsx, example/src/tabView/CustomTabBarExample.tsx, example/src/tabView/TabBarIconExample.tsx, example/yarn.lock, fabricexample/package.json, fabricexample/src/tabView/CustomIndicatorExample.tsx, fabricexample/src/tabView/CustomTabBarExample.tsx, fabricexample/src/tabView/TabBarIconExample.tsx, fabricexample/yarn.lock, package.json, src/PagerView.tsx, yarn.lock
Fixes incorrect safe area for iOS examples.
Aditionally, updates "@types/react" as it was on older version which resulted in type errors. iOS pod for react-native-pager-view was bumped to latest version.
Check if modified examples are working correctly on Android and iOS
=> Fix safe area in examples

example/src/KeyboardExample.tsx, example/src/component/NavigationPanel/LogsPanel.tsx, example/src/component/NavigationPanel/NavigationPanel.tsx, example/src/hook/useNavigationPanel.ts, fabricexample/ios/Podfile.lock, fabricexample/src/KeyboardExample.tsx, fabricexample/src/component/NavigationPanel/LogsPanel.tsx, fabricexample/src/component/NavigationPanel/NavigationPanel.tsx, fabricexample/src/hook/useNavigationPanel.ts
- Fix duplicated key in logs panel
- Use `TouchableOpacity` from RN instead of react-native-gesture-handler, on Android it did not work. It was caused by missing setup from these docs: https://docs.swmansion.com/react-native-gesture-handler/docs/installation#usage-with-modals-on-android . Based on the info from @troZee we don't need it, so I changed it to one provided by RN.
- Add missing testId to simplify tests written in Maestro
- Prevent removing last page
1. Validate that events generated in logs panel do not trigger duplicated key warning.
2. Verify that control tab works correctly on Android.
3. Verify that removing last page does not remove page if only 1 is present
=> Fix issues reported by QA

example/src/App.tsx, fabricexample/src/App.tsx
Goal of this PR is to make it easier to test RTL / LTR directions for provided examples.
Launch example app switch LTR to RTL.
=> feat: add button to quickly switch layout direction

android/src/main/java/com/reactnativepagerview/event/PageSelectedEvent.kt
The change unifies the behaviour of the onPageSelected event on Android to work in the same way as on iOS. 
On iOS, coalescing key is always new for each onPageSelected event:
Before this change, a quick swipe on Android caused some events to be missed, resulting in JS not being informed of each page change.
Negative impact: may slightly degrade performance on android (depending on how the code is written)
Start swiping fast. Check the incoming "position" in onPageSelected event (it should be incrementing, without holes).
=> Stop debouncing onPageSelected event on Android

android/build.gradle, android/src/main/AndroidManifest.xml
Starting from React Native v0.73 , all libraries will need to be updated with these two one-liners due to Android Gradle Plugin upgrade
[discussions-671](https://github.com/react-native-community/discussions-and-proposals/issues/671)
=> feat(android): 🌟 add support for React Native 0.73

ios/ReactViewPagerManager.m
Rename `setScrollEnabled` to `setScrollEnabledImperatively` to fix setting scroll enabled by calling a method on ViewPager ref. 
Currently when calling `ref.current?.setScrollEnabled(false);` we get this error message: 
This was left over from the new arch migration. Fixes: #750
Currently when 
Render this button in basic example and check if it works. 
```jsx
<Button
title="Set scroll enabled imperatively"
onPress={() => {
ref.current?.setScrollEnabled(false);
}}
/>
```
=> fix: rename setScrollEnabled to setScrollEnabledImperatively on old arch

ios/Fabric/RNCPagerViewComponentView.mm, ios/ReactNativePageView.m
Sometimes when navigating between pages (using TabBar) view state was getting out of sync, to be specific the `view.animating` was being set to true when it wasn't animating. This was happening when user was pressing multiple times on the same item. 
Therefore, this check was met: 
```objc
if (!animated || !view.animating) {
[view goTo:index.integerValue animated:animated];
}
```
Which caused pager view to be stuck on the same page. This check prevents this from happening. Reported here: https://github.com/react-navigation/react-navigation/issues/10425
Go to TabView example and click on the same tab bar item multiple times. Check that it stops on the early return.
=> fix: return when user navigates to the same page

ios/Fabric/RNCPagerViewComponentView.mm
Fixes: #765 
This check is not needed for Fabric as those commands are executed synchronously. 
Check if Fabric example renders correctly
=> fix(iOS): remove current index check

android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt, android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
This PR removes a redundant `PageSelectedEvent` dispatch causing an ANR on RN 0.72.
Closes #752 
In the following function:
https://github.com/callstack/react-native-pager-view/blob/2946c1c33df6cacc8f9f77220bb879b39bb75ace/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt#L167-L182
On the new architecture, using RN 0.72, the event in L178-L180 is dispatched with an incorrect `view.id` of `-1` which apparently trips React Native up causing a silent error leading to an ANR.
One way to fix it is to adjust the ID used with this dispatch, e.g. by replacing `view.id` with `root.id`, which contains the correct ID value, which solves the issue.
However, the `PagerViewViewManagerImpl.setCurrentItem(...)` call in L176 also (implicitly) triggers a `PageSelectedEvent` dispatch, …
=> fix(android): remove the redundant `PageSelectedEvent` dispatch causing an ANR on RN 0.72

example/ios/Podfile.lock, example/package.json, example/yarn.lock
This is the update of the RN version to show that the following issue is gone:
https://github.com/callstack/react-native-pager-view/issues/774
Compile and test against platforms. 
=> chore: bump RN version to 0.72.6 in the example

android/build.gradle
Upcoming react-native 0.73+ includes android gradle plugin 8+ which needs namespace in build.gradle but also needs buildFeatures.buildConfig enabled as well for modules that use it
It is not sufficient to enable this at the top-level app build.gradle, specific modules that use it (such as those that implement new architecture, it seems) must also enable it at the module level
This change was necessary and is in-use in my work app via patch-package as I work through android-gradle-plugin 8+ issues in prep for react-native 0.73 launching for everyone
It should be backwards compatible with older gradle plugins in the exact same way the previous namespace change was, as it is wrapped in the same conditional
It is similar to changes I needed to do as react-native-firebase maintainer --> …
=> fix(android): add buildFeatures.buildConfig on for AGP8+ compatibility

ios/Fabric/RNCPagerViewComponentView.mm, ios/ReactNativePageView.h, ios/ReactNativePageView.m, react-native-pager-view.podspec
This PR adds support for `visionOS`. Using compiler conditionals to prevent compiling unavailable APIs.
https://github.com/callstack/react-native-pager-view/assets/52801365/fa12de6f-d3c3-47b4-9727-9f3fc068bc26
1. Init visionOS app: `npx @callstack/react-native-visionos init App`
2. Add pager-view 
3. Check if everything works
Xcode 15.1 Beta
=> feat: add support for visionOS

android/src/main/java/com/reactnativepagerview/ViewPagerAdapter.kt
We are using "react-native-tab-view" in Dream11 App. We were not able to reproduce the crash, But we are seeing crash instance in firebase. We can see that partial [fix](https://github.com/callstack/react-native-pager-view/blob/d0b77b33140e5492cfd6438b55f80bdf957dd9c5/android/src/main/java/com/reactnativepagerview/ViewPagerAdapter.kt#L48) of this is already merged in **react-native-tab-view**.  This fix works only if **removeChildAt** of **ViewPagerAdapter** gets called from **removeChild** of **ViewPagerAdapter**.  The existing fix won't work [here](https://github.com/callstack/react-native-pager-view/blob/d0b77b33140e5492cfd6438b55f80bdf957dd9c5/android/src/main/java/com/reactnativepagerview/PagerViewViewManagerImpl.kt#L72). This PR takes care of boundary conditions of childrenViews …
=> fix(android): index out of bounds crash

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/main.yml
Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
just run workflows...
=> Node.js 16 actions are deprecated.

src/PagerView.tsx
React Native pager view emits an error when used with Nightlies on the New Architecture with and without the Bridge.
The reason is that Pager View copied a [work around we also have in ScrollView](https://github.com/callstack/react-native-pager-view/blob/master/ios/Fabric/RNCPagerViewComponentView.mm#L362-L368) to allow apps to implement complex animations, like parallax animations, but it forgot to add the JS side of it, that makes the workaround effective.
The JS part is to make sure that `RCTEventEmitter` is properly registered as CallableModule in the JS side.
This PR adds that bit, copying what ScrollView does.
_For context, we are not happy with this workaround. We still have to figure out properly how to fix it and, as soon as we know, we are going to provide guidance and/or submit …
=> [Fix] Make sure that RCTEventEmitter is registered before emitting the first event

ios/RNCPagerView.m
This PR fixes issue causing `PagerView` to freeze after calling `goTo` to same index (Paper arch only)
Fixes #803 
1. Open any example with tab
2. Tap on currently selected tab
3. Pager should be scrollable
=> fix(ios): fix freezing when navigating to same index

src/LEGACY_PagerViewNativeComponent/LEGACY_PagerViewNativeComponent.ts, src/PagerView.tsx, src/PagerViewNativeComponent/PagerViewNativeComponent.ts
This fixes a compatibility issue with React Native >0.73.
The export has to be named "Commands", otherwise it will cause this error:
```
error: node_modules/react-native-pager-view/src/PagerViewNativeComponent/PagerViewNativeComponent.ts:
/[...]/node_modules/react-native-pager-view/src/PagerViewNativeComponent/PagerViewNativeComponent.ts:
Native commands must be exported with the name 'Commands'
```
Only the export names are changed. No functional change.
=> fix(js): Native commands must be exported with the name 'Commands'

src/PagerView.tsx
Fixes https://github.com/callstack/react-native-pager-view/issues/823
React.forwardRef typing does not allow simple usage of component as a ref type. This PR brings backward compatibility of Ref<PagerView>.
Test PagerView component, ref, props typing.
=> (#823) Export PagerView type

.github/workflows/android.yml, .github/workflows/ios.yml
=> Fix workflows

src/PagerView.tsx
6.3.1+ versions now require the `useNext` prop as reported in #837. This marks it back as optional.
n/a - type only.
n/a - type only.
| iOS     |    n/a     |
| Android |    n/a     |
=> Make useNext optional

src/PagerView.tsx
Remove workaround for properly registering `RCTEventEmitter` https://github.com/facebook/react-native/pull/44474/files
`Just trust me`
=> Remove RCTEventEmitter workaround

android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt, android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
Fixes https://github.com/callstack/react-native-pager-view/issues/850 and https://github.com/callstack/react-native-pager-view/issues/856.
As stated in the first issue, there seem to be unneeded nullabilities in `child` arguments for Android PagerViewManager (both paper and fabric). Their existence makes the methods override nothing, which in turn crashes the build.
Run on a fresh android app.
Having anything `react-native-pager-view` related in the app.
You need to create 2 differents apps - one with RN 0.74, the other with RN 0.75 - to make sure we don't lose <0.75 compatibility. Then, after installing dependencies just try building via Android Studio.
| iOS     |    not relevant     |
=> Fix child argument types in `addView` methods

ios/RNCPagerScrollView.h, ios/RNCPagerView.h, ios/RNCPagerView.m
This PR fixes visionOS builds.
Run the example app on visionOS
visionOS Simulator
Build
=> fix: visionOS builds

ios/Fabric/RNCPagerViewComponentView.mm, ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …
=> feat: add load method

src/utils.tsx
=> Fix newArch issue with no feedback on android

ios/Fabric/RNCPagerViewComponentView.mm, ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
Since …
=> feat: remove usage of currentBridge

android/build.gradle
Closes https://github.com/callstack/react-native-pager-view/issues/879 
Closes https://github.com/callstack/react-native-pager-view/issues/744
Closes https://github.com/react-navigation/react-navigation/issues/11473
Closes https://github.com/callstack/react-native-pager-view/issues/692
=> chore(android): bump android ViewPager2 to 1.1.0

ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.h, ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm, ios/LEGACY/LEGACY_RNCPagerView.h, ios/LEGACY/LEGACY_RNCPagerView.m, ios/UIView+isHorizontalRtlLayout.h, ios/UIView+isHorizontalRtlLayout.m
When in RTL, vertical pager view is scrolling backwards. This is unwanted behavior (only horizontal axis should be inverted in RTL).
Test LTR & RTL in legacy pager view.
=> fix(ios): Fix vertical list scroll directionin rtl

android/src/main/java/com/reactnativepagerview/PagerViewViewManagerImpl.kt
=> fix(android) Fix crash with navigation on fabric 

example/src/HeadphonesCarouselExample.tsx, ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
This PR fixes issue with views not being correctly recycled on new arch, causing components styles miscalculations
1. Open example app
2. Navigate through examples a lot – e.g `BasicExample` -> `PaginationDotsExample` -> `HeadphonesExample` -> again `PaginationDotsExample` etc.
3. No layout issues should appear, rest should work as before
=> fix(iOS): fix component layout issue

example/src/App.tsx, example/src/tabView/NestedTabViewExample.tsx, ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm, ios/LEGACY/LEGACY_RNCPagerView.m
Currently scroll over legacy pager view is not working while nested inside scroll view.
Nesting might be necessary while we have big header which you don't want to be visible while you are swiping pages.
The issue arise with [6.2.0 version](https://github.com/callstack/react-native-pager-view/commit/769a3a21500fbe40c1909c9bf50f724c76a5b435#diff-b76afe0b22639c5e44b27b49c147284272978b94c8975b572b7a10cf8a3f5ba6R18) and support for navigate back gesture.
I've tested that navigate back gesture and it didn't worked for me as you may see on attached video.
I've also checked if basic react native ScrollView supports that for horizontal mode and it's not.
Based on all above I believe it's not worth to block users and I reverted that change.
I think we can revisit that use case later and fix that …
=> fix(#722): revert not working back navigation gesture in favour of PagerView inside ScrollView

ios/Fabric/RNCPagerViewComponentView.mm
This PR fixes issue causing component to freeze when layout was updated during transition
When layout was updated e.g. because of hiding keyboard, `setViewControllers` completion block was never called, which resulted in swipe being disabled
It fixes this issue by preventing layout update during transition phase and updating it after transition ends
1. Build the example app.
2. Go to the Keyboard Example menu.
3. Touch the TextInput to show the keyboard.
4. Press the `Next` page button. (might be required to modify `ControlPanel` to move button above keyboard)
6. Should navigate correctly, should be able to interact
Other examples should work as before
=> fix(fabric): prevent freeze on layout update during transition

android/src/main/java/com/reactnativepagerview/ViewPagerAdapter.kt
This PR fixes issue causing crash on Android - both architectures
Fixes #942 #859 #173 
=> fix(android): prevent views from being recycled

package.json
When installing this package with RN 0.77 there's a warning related to the missing field in `codegenConfig`, this PR fixes it 👍
1. Create an app with 0.77
2. Apply diff from this PR
3. The warning shouldn't be no longer produced
RN 0.77
Running `pod install`.
=> feat: add component provider field for codegen

android/src/main/java/com/reactnativepagerview/NestedScrollableHost.kt
This PR fixes a bug on Android where taps sometimes incorrectly trigger while swiping between pager screens, see issues https://github.com/callstack/react-native-pager-view/issues/960 and https://github.com/callstack/react-native-pager-view/issues/954. These issues in turn were opened in order to investigate https://github.com/bluesky-social/social-app/pull/7312
The cause of the bug seems to have had to do with React not being notified when the native pager starts scrolling, which meant that it didn't properly cancel gestures in the pager's children.
The fix involves adding a call to [notifyNativeGestureStarted](https://github.com/facebook/react-native/blob/c65117eba9f16da023e99253bfe28c0858f332fd/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/NativeGe …
=> fix(android): prevent taps while scrolling

android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt, android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
This PR applies necessary changes for RN 0.79. Before this change the library won't compile on android on RN 0.79. This change is needed because of [this](https://github.com/facebook/react-native/commit/5a290c4cab6f58744a9252687feefd8b6a8d3305) commit in `react-native`.
- clone [this](https://github.com/MatiPl01/react-native-pager-view-issues) repo (clean app with RN 0.79-rc.3 and latest `react-native-pager-view`)
- `git clone https://github.com/MatiPl01/react-native-pager-view-issues.git`
- `cd react-native-pager-view-issues && git switch 0.79-android-build`
- build the app for android and observe the error (`Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.`)
- install library witch changes from this PR
- `npm install …
=> fix: Remove nullability of command id

example/src/App.tsx, example/src/tabView/TabViewInsideScrollViewExample.tsx, ios/Fabric/RNCPagerViewComponentView.mm, ios/RNCPagerView.m
Currently scroll over legacy pager view is not working while nested inside scroll view.
Nesting might be necessary while we have big header which you don't want to be visible while you are swiping pages.
The issue arise with [6.2.0 version](https://github.com/callstack/react-native-pager-view/commit/769a3a21500fbe40c1909c9bf50f724c76a5b435#diff-b76afe0b22639c5e44b27b49c147284272978b94c8975b572b7a10cf8a3f5ba6R18) and support for navigate back gesture.
I've tested that navigate back gesture and it didn't worked for me as you may see on attached video.
I've also checked if basic react native ScrollView supports that for horizontal mode and it's not.
Based on all above I believe it's not worth to block users and I reverted that change.
I think we can revisit that use case later and fix that …
=>  fix(722): revert not working back navigation gesture in favour of PagerView inside ScrollView

ios/RNCPagerViewComponentView.mm
This PR cleans up the code for iOS implementation. 
- Move retrieval of event emitter to one shared function, (same as built-in React Native modal)
- Use `#pragma mark` for logic grouping of code
- Simplify conditions in `scrollViewDidScroll`
Test if everything works the same
=> fix(iOS): cleanup the code, split into smaller functions

example/src/App.tsx, example/src/NestedHorizontalScrollViewExample.tsx, ios/RNCPagerViewComponentView.mm
This PR fixes pager being moved by nested scroll views. 
When embedding a horizontal scroll view into a (horizontal) pager view dragging on the scroll view can cause pager's scroll view to move. Before the onScroll event wasn't setting destination index in that case which made it report incorrect position.
https://github.com/user-attachments/assets/898d704d-4ca2-4bcc-8cef-a5796a1a9005
Pay close attention to this progress bar 👆
https://github.com/user-attachments/assets/c5f7bb30-4dda-4207-a0a8-61d786e05653
Check new horizontal scroll example
=> fix: pager reporting incorrect position when being moved by nested scroll view
