callstack/react-native-pager-view

js/AndroidViewPagerNativeComponent.js, js/ViewPagerAndroid.android.js, js/ViewPagerAndroid.ios.js
=> Fix imports (haste)

package.json, typings/index.d.ts
imported from @types/react-native
fixes #6
=> added typings

example/ViewPagerAndroidExample.android.js
- move pages data to state, 
- add button with handler to add new page dynamically to ViewPager,
- change ProgressBar to calculate progress with dynamic number of pages.
Closes #4.
=> Add to examples button that dynamically attach new view to ViewPager

.npmignore, js/index.js
* Fixes #12 (no need to add what we already have in `.gitignore`
* Fixes #13
=> Add .npmignore and fix compatibility with Jest

.npmignore
=> Exclude viewpager.gif to reduce bundle size

RNCViewpager.podspec, ios/RNCViewpager.podspec, package.json
Fix: #20 
Fixes podspec errors.
Some attributes are referenced from package.json.
=> Fixes podspec errors.

ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m
Implement onPageScrollStateChanged on iOS
=> Implement onPageScrollStateChanged on iOS

ios/ReactNativePageView.m
=> fix: scrollEnabled prop breaks a touch event

README.md
Added:
* Api section 
Changed:
* Description 
* Linking instruction
=> Update docs for 2.0

CHANGELOG.md, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, js/types.js
=> chore: remove peekEnabled property

example/ViewPagerExample.js
Add orientation and transitionStyle as iOS props to example
=> chore: Add orientation and transitionStyle to example

js/ViewPager.js
=> fix: rename AndroidViewPager in favour of RNCViewPager for Android too

.circleci/config.yml, .eslintrc.js, .prettierrc.js, babel.config.js, example/ViewPagerExample.js, example/index.js, example/src/component/Button.js, example/src/component/LikeCount.js, example/src/component/ProgressBar.js, example/utils.js, js/ViewPager.js, js/ViewPagerNativeComponent.js, js/index.js, js/types.js, js/utils.js, package.json, yarn.lock
=> feat: add eslint

README.md, example/ViewPagerExample.js, js/types.js, typings/index.d.ts
Describe showPageIndicator prop in documentation. 
Close https://github.com/react-native-community/react-native-viewpager/issues/79
=> chore: add showPageIndicator prop to doc

ios/ReactNativePageView.m
* The UIPageControl element added to the view hierarchy manually doesn't cycle through views when tapped. This is because the event has to be added manually. The built in UIPageControl element from UIPageViewController does this automatically, however that's not being used in this project.
* The fix adds a control event hook UIPageControl when the value changes. This is triggered when the user taps it. 
The current behavior is as such:
With the fix:
- Add an set of views to **react-native-viewpager**
- Set **showPageIndicator** to **true**
- Tap the UIPageControl itself, observe that the dots update but the views do not
- Add an set of views to **react-native-viewpager**
- Set **showPageIndicator** to **true**
- Tap the UIPageControl itself, behavior works now as expected
| OS      | …
=> Fixes tapping on UIPageControl to cycle through pages

js/utils.js
=> Remove useless warning while overriding children' style

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, android/src/main/java/com/reactnativecommunity/viewpager/VerticalViewPager.java
VerticalPager for android, same as ios, ideas come from 
[DeskClock](https://android.googlesource.com/platform/packages/apps/DeskClock/+/master/src/com/android/deskclock/VerticalViewPager.java)
[Vertical ViewPager with HorizontalScrollView inside Fragment](https://stackoverflow.com/questions/46828920/vertical-viewpager-with-horizontalscrollview-inside-fragment)
No js codes changed, keep it clean.
=> Android VerticalPager

.flowconfig, example/android/app/build.gradle, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/main/java/com/reactnativecommunity/viewpager/example/MainApplication.java, example/android/app/src/main/java/com/reactnativecommunity/viewpager/example/ReactNativeFlipper.java, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/gradlew, example/index.js, example/ios/Podfile, example/ios/Podfile.lock, example/ios/ViewPagerExample-Bridging-Header.h, example/ios/ViewPagerExample.xcodeproj/project.pbxproj, example/ios/ViewPagerExample.xcodeproj/xcshareddata/xcschemes/ViewPagerExample-tvOS.xcscheme, example/ios/ViewPagerExample.xcodeproj/xcshareddata/xcschemes/ViewPagerExample.xcscheme, example/ios/ViewPagerExample.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, example/ios/postinstall.sh, js/types.js, package.json, react-native.config.js, yarn.lock
Example needs to be updated to the newest react native version, which is 0.62.x
Closes https://github.com/react-native-community/react-native-viewpager/issues/159
* Run on both platforms
| iOS     |    ✅   |
=> chore: update example to latest react native

.circleci/config.yml, example/android/app/build.gradle, package.json, release-it.json, yarn.lock
Add `release-it` to automate release process. 
run `yarn release-it --dry-run` in project dir
=> chore: configure release-it

ios/ReactNativePageView.m
Fixes https://github.com/react-native-community/react-native-viewpager/issues/207
=> fix(ios): don’t divide by zero

android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java
This PR fixes https://github.com/react-native-community/react-native-viewpager/issues/211 which was a bug preventing pages from being deleted on Android.
The solution was to override `getItemId()` in `FragmentAdapter.java` to provide a unique ID (as opposed to the item position, which was the default). See https://stackoverflow.com/a/26944013/2904572
I also had to update the `createFragment` method `FragmentAdapter` to return a new Fragment on each call. Since we keep the internal views around anyway I think this is fine (and a new fragment is always expected as per the Android docs as far as I can tell). 
> _"Make sure that your new createFragment() method always supplies a new fragment instance each time the function is called instead of reusing instances"_ …
=> fix (android): #211 pages can now be removed on Android

android/src/main/java/com/reactnativecommunity/viewpager/FragmentAdapter.java
Fixes page list mutation on android.  Enables implementation of lazy rendering.
```tsx
export function ViewerScreen() {
return (
<LazyViewPager
data={'abcdefghijklmnop'.split('')}
style={{backgroundColor: 'white', flex: 1}}
renderItem={({item, itemIndex, visiblePage}) => {
console.log(
'ViewerScreen renderItem item: ' +
item +
' itemIndex: ' +
itemIndex +
' visiblePage: ' +
visiblePage,
);
return <Text style={{fontSize: 200}}>{item + ' ' + item}</Text>;
}}
/>
);
}
```
```tsx
import React, {useState} from 'react';
import {NativeSyntheticEvent, StyleProp, View, ViewStyle} from 'react-native';
import ViewPager, {
ViewPagerOnPageSelectedEventData,
} from '@react-native-community/viewpager';
type PageSelectedEvent = NativeSyntheticEvent<ViewPagerOnPageSelectedEventData>;
type RenderItem<T> = …
```
=> Android: Fix children list mutation

.flowconfig, example/ViewPagerExample.js, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/gradlew, example/android/gradlew.bat, example/ios/Podfile, example/ios/Podfile.lock, example/ios/RNPod.rb, example/ios/ViewPagerExample.xcodeproj/project.pbxproj, example/src/component/LikeCount.js, js/ViewPagerNativeComponent.js, js/utils.js, package.json, yarn.lock
upgrade react-native dep in example to 0.63
Just run ios/android and check, if everything works. 
=> chore: upgrade react-native in example to 0.63

.npmignore, package.json
Hot-fix to allow deploy proper deploy
=> hotfix: package version and name

example/src/App.tsx, tsconfig.json
=> hotfix: Change example package name

android/src/main/java/com/reactnativecommunity/viewpager/VerticalViewPager.java
Fix android device orientation change issue.
Repo step:
1. Run any project with viewPager and pageMargin set to none zero value on android device.
2. Swipe/Scroll a few pages
3. Change the orientation from portrait to landscape or from landscape to portrait.
Expected: View pager content properly aligned
Actual: The current page is offset.
The problem is inside the android viewPager source code: `onSizeChanged`. 
It has following code:
```
if (w != oldw) {
recomputeScrollPosition(w, oldw, mPageMargin, mPageMargin);
}
```
`w` is always not equals `oldw` when changing orientation, so `recomputeScrollPosition` is called. 
And in `recomputeScrollPosition`, it always adds the page margin.
```
final int widthWithMargin = width - getPaddingLeft() - getPaddingRight() + margin;
final int …
```
=> fix: android device orientation change page margin issue

README.md
https://github.com/callstack/react-native-viewpager/issues/280
=> feat: add example link to readme

src/utils.tsx
=> cherry-pick of #284

android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, src/types.ts
=> feat(android): implement offscreenPageLimit prop

package.json, yarn.lock
=> chore: update bob

README.md
I added known issues section to avoid any confusion
=> chore:  add known issues section to readme

README.md, android/gradle.properties, android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java, example/android/build.gradle, src/types.ts
Supporting negative values let's us have pages peek from the previous and next pages.
=> feat: support negative values for pageMargin on Android

android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
Solves #309. Adds missing null assertion that generates a build error when using RN 0.64.0+
Have a RN project with this library as a dependency
Run the project with `npm run android`.
=> Fixed build error on RN 0.64.0+

android/build.gradle
Fixes https://github.com/callstack/react-native-pager-view/issues/318
Build passes
Can run `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`
Run `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`
| iOS     |    NA     |
=> Fix of #318

example/ios/Podfile.lock, example/package.json
=> fix(e2e): change test butler url

src/types.ts
=> Update typo in types.ts

src/types.ts
Suggestion for issue #341
N/A
N/A
=> feat: add missing `onStartShouldSetResponder` method

example/ios/Podfile.lock, ios/ReactNativePageView.m
https://github.com/callstack/react-native-pager-view/issues/330
This PR fixes the inconsistent scroll position and offset on iOS.
It now behaves just like android.
https://user-images.githubusercontent.com/50402950/118653848-38501480-b7e8-11eb-95ce-7b196a481911.mp4
Build the Example app and try to change swipe directions on the  `Headphones Carousel Example`
=> fix(ios): Changing swipe direction flickers (#330)

example/src/BasicPagerViewExample.tsx, ios/ReactNativePageView.h, ios/ReactNativePageView.m, ios/ReactViewPagerManager.m, src/LazyPagerView.tsx, src/PagerView.tsx
Enables pages to be rendered on demand, instead of all at once. This is the iOS native code changes.
Split from #279. Note that this builds on top of #331, so when reviewing code, may be easier to check the specific commits that are not in #331.
- Checkout of this branch (unmodified).
- Checkout of this branch, patched to show renders.
<details>
<summary><tt>track-page-renders.patch</tt></summary>
```diff
diff --git a/example/src/BasicPagerViewExample.tsx b/example/src/BasicPagerViewExample.tsx
index 48ad5a4..69df7a3 100644
--- a/example/src/BasicPagerViewExample.tsx
+++ b/example/src/BasicPagerViewExample.tsx
@@ -15,6 +15,17 @@ function keyExtractor(page: CreatePage) {
}
function renderItem({ item }: { item: CreatePage }) {
+  return <TrackingRender item={item} />;
+}
+
+function …
```
=> Lazy pager (iOS native side)

example/src/utils.ts
Image on the keyboard example pointed to 404 URL
This PR fixes the logo URL.
Open `Keyboard Example` and see the image is displayed properly
=> fix: logo URL in the keyboard example

ios/ReactNativePageView.m
Close https://github.com/callstack/react-native-pager-view/issues/421
The native component does not handle a such case, where user can scroll to n page, where n > 1. To fix this issue, I used workaround and call `setPage` method for each page, which should be displayed 
eg. 
current index:0 
next index: 4 
call setPage(1)...setPage(4)
This fix unifies the behaviour for both platforms. 
* Go to OnPageScroll Example 
* Play with tabs
| iOS     |    ✅   |
https://user-images.githubusercontent.com/12766071/132377263-6f201f62-c836-4441-ba34-f95370b08baa.mov
=> fix(ios): onScroll callback values

android/src/main/java/com/reactnativepagerview/NestedScrollableHost.kt, android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt, example/src/App.tsx, example/src/NestPagerView.tsx
fix Issue (#303)
See [here](https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt)
I only tested example project. Looks okay.
=> fix(android): nested pager view 

ios/ReactNativePageView.m
Fixes #465
Prevent crash when removing one or many pages at a time
=> fix(ios): Prevent removal of one or many pages at a time

ios/ReactNativePageView.m
Fix crash with `NSInternalInconsistencyException` on iOS
=> fix crash with `NSInternalInconsistencyException` on iOS

README.md
there was a named import of view pager in docs which was incorrect, therefore i fixed it by using default import
you can test name import `import { PagerView } from "react-native-pager-view";` you will get error, after default import, this error will remove
you can read Test Plan
you can read Test Plan
=> docs: fix PagerView import

android/src/main/java/com/reactnativepagerview/ViewPagerAdapter.kt
Fix #173 
1. yarn add `@react-navigation/native-stack`.
2. `goBack` when `PageView screens` is scrolling.
- [] I added the documentation in `README.md`
- [] I updated the typed files (TS and Flow)
=> fix(android): #173

ios/ReactNativePageView.m
Fixes  https://github.com/callstack/react-native-pager-view/issues/315
- This PR adds a gesture failure logic on scroll view used by pager if pop gesture is triggered on iOS.
- It checks if a navigation controller is present and adds [requireGestureRecognizorToFail](https://stackoverflow.com/questions/21928023/may-i-know-what-exactly-requiregesturerecognizertofail-will-do) on ScrollView used by Pager view.
- Created a [repo](https://github.com/intergalacticspacehighway/pager-view-ios-swipe-back-fix) with the fix. App.js includes react navigation code with pager view in `ProfileScreen`
- Test the app with and without react navigation. The swipe to go back gesture should work as expected
https://user-images.githubusercontent.com/23293248/149651316-e1e7eafe-7d03-4204-b9ef-eddb6e1bb873.mov
- …
=> fix: disable pager scroll gesture on swipe to go back

ios/ReactNativePageView.m
Fixes #523
Fixes #543
See https://github.com/callstack/react-native-pager-view/pull/518#issuecomment-1129897222 for more info.
See repro at: https://github.com/callstack/react-native-pager-view/pull/518#issuecomment-1129810948
=> fix: pager sometimes does not fill full height

example/src/App.tsx, package.json, src/PagerView.tsx, src/PagerViewViewNativeComponent.ts, src/types.ts
This pull request sets up codegen spec for further work on fabric migration.
=> Setup codegen spec & fix types

README.md
This PR adds info about new architecture to README.
=> chore: add fabric seciton to docs

.github/actions/install-dependencies/action.yml, .github/workflows/android.yml, .github/workflows/ios.yml
Added cache restore when cache keys are missing.
Run CI
=> fix: reinstall yarn on cache miss on CI

example/android/gradle.properties, example/ios/Podfile.lock, fabricexample/android/gradle.properties, fabricexample/ios/Podfile.lock, ios/Fabric/RNCPagerViewComponentView.h, ios/Fabric/RNCPagerViewComponentView.mm, ios/ReactNativePageView.h, ios/ReactNativePageView.m, yarn.lock
This pull request fixes indicator animation issue on _setPage_ method call on **iOS**. 
When calling _setPage_ method to page which was more than 1 index away for current one, indicator wasn't smoothly animating to new index.
Pull request also fixes incorrect offset value issue, which was causing indicator to "jump" a bit on page change.
Also fixes transition animation issue on **Paper** arch, which was causing to show transition animation from wrong page when navigating with _setPage_ method.
Fixes #636 
1. open paper/fabric example app
2. open `Basic Example`
3. navigate to last page by pressing `Last` on navigation panel
4. indicator should animate correctly
=> Fix indicator animation on setPage

.github/workflows/ios.yml, example/ios/Podfile, fabricexample/ios/Podfile
=> chore(CI): turn off flipper on CI

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/main.yml
This pull request changes every workflow trigger to run on _pull request_ or _push_ to **master** branch.
=> chore: change CI workflows trigger

src/PagerViewNativeComponent.ts
This PR fixes onPageScroll event type to `DirectEventHandler` this had no impact on App performance since the dispatched event was direct. Only the type was wrong. 
Run the App.
| Android |    ✅   |
=> fix: change onPageScroll type to direct

example/src/App.tsx, fabricexample/src/App.tsx
This is a copy of #717 but for next branch.
=> v7.0.0 feat: add button to quickly switch layout direction

example/src/App.tsx, example/src/BasicPagerViewExample.tsx, example/src/KeyboardExample.tsx, example/src/NestPagerView.tsx, example/src/OnPageScrollExample.tsx, example/src/OnPageSelectedExample.tsx, example/src/PaginationDotsExample.tsx, example/src/ReanimatedOnPageScrollExample.tsx, example/src/ScrollViewInsideExample.tsx, example/src/ScrollablePagerViewExample.tsx, example/src/component/LikeCount.tsx, example/src/component/ProgressBar.tsx
Test ids will be used to e2e tests written in Maestro
=> chore: add test id to the example

README.md
The pager already supports the new arch on the main branch 
Just read it
=> chore(readme): remove new architecture section

example/ios/Podfile, example/package.json, package.json
This PR adds fabric scripts to example to easily run the app on new architecture.
=> chore: add fabric scripts

ios/Fabric/RNCPagerViewComponentView.mm, ios/RNCPagerView.m
Fix broken overdrag (not returning to prev place) when swiper is rendered on notch
render swiper with absolute position on entire screen on iPhone with notch
https://github.com/callstack/react-native-pager-view/assets/16975059/311107b1-32c0-4f51-9adc-ede41785fba7
=> swiper 7.0: fix broken overdrag on notch

ios/Fabric/RNCPagerViewComponentView.h, ios/Fabric/RNCPagerViewComponentView.mm, package.json, react-native-pager-view.podspec
This PR fixes fabric builds which probably got broken during a merge of `next` branch.
Launch the app check if everything works properly
=> fix: fabric builds

ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
**Related issues:** https://github.com/callstack/react-native-pager-view/issues/852, https://github.com/Expensify/App/issues/41810
**Proposal:** https://github.com/Expensify/App/issues/41810#issuecomment-2248527381
Build the examples with the new architecture.
1. Run the iOS examples app.
2. Open the Basic Example.
3. Click the `Control` tab.
**Expected result:** the background should fill the available space.
**Before the fix:**
https://github.com/user-attachments/assets/d3eaa71d-ad94-4498-969b-589d2c8bcc5b
**After the fix:**
https://github.com/user-attachments/assets/a02964b4-90f0-4fa9-ae9b-84d7b6cbb90a
=> fix(ios): update content view frame based on new layout metrics

ios/Fabric/RNCPagerViewComponentView.mm
=> Change RNCViewPagerComponenDescriptor import

example/package.json, example/yarn.lock
=> Fix android newArch build

README.md, example/src/App.tsx, example/src/PagerHookExample.tsx, src/PagerView.tsx, src/index.tsx, src/usePagerView.ts, src/useViewPager.ts
=> feat(js): add view pager hook

maestro-tests/basic_example/tc14_pager_basic_example.yaml.yaml
=> chore(CI): Fix maestro tests for iOS workflows

ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.h
Fixing regression from rtl pr 
=> fix(ios): Fix fabric builds for iOS

ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
Closes:  https://github.com/Expensify/App/issues/50349 https://github.com/callstack/react-native-pager-view/issues/597 https://github.com/callstack/react-native-pager-view/issues/791
=> fix(ios): Fix adding new page after pager is mounted

example/android/gradle.properties, example/ios/Podfile, example/ios/Podfile.lock
Switching CI workflow to build using new arch
=> chore(CI): Switch CI jobs to fabric

example/package.json, package.json
=> chore(scripts): Fix bootstrap scripts

.github/actions/install-dependencies/action.yml, .github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/main.yml, package.json
Switch CI to use `Bun` instead of `Yarn`
`Just create more PR's`
| iOS     |    ✅   |
| Android |    ✅   |
=> chore(cli): swap yarn to bun

README.md
=> chore(docs): Update Readme

ios/LEGACY/Fabric/LEGACY_RNCPagerViewComponentView.mm
=> fix(ios): Fix on add new dynamic page

.github/workflows/ios.yml, package.json
=> chore(ci): Change iOS simulator version

example/src/BasicPagerViewExample.tsx
Cleanup BasicExample to work with rtl layout direction.
Before:
https://github.com/user-attachments/assets/af4a60f1-76ab-43b2-8aef-6eb0f5f20fc7
After:
https://github.com/user-attachments/assets/d74c9b79-eb0c-4289-979f-c4d1401c1145
=> fix(example): Fix BasicExample to work with RTL

ios/Fabric/RNCPagerViewComponentView.mm
Before: 
https://github.com/user-attachments/assets/985cc26d-d6cd-47ca-901c-3205d46133bc
After: 
https://github.com/user-attachments/assets/285ebd80-602f-4ee8-a908-0feb46bd2c6e
=> fix(ios): Fix progress bar movement on RTL & Fabric

example/src/PagerHookExample.tsx, src/usePagerView.ts
=> fix(js): Fix usePagerView methods

android/src/main/java/com/reactnativepagerview/PagerViewViewManagerImpl.kt
Before:
https://github.com/user-attachments/assets/8f931719-72f8-4abf-8432-2ad091429425
After:
https://github.com/user-attachments/assets/2fb7fdc7-d0a0-430f-8f91-b8a7bf17e0a3
=> fix(android): Fix blank screen after removal of last page

ios/RNCPagerView.m
=> refactor(iOS): Update React imports

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/main.yml
Pins all action to specific commit SHA instead of version
=> chore: pin actions to commit SHA
